# Generated by Django 4.2.1 on 2023-05-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../p5/images/default_profile_qveugj', upload_to='images/'),
        ),
    ]
