# Generated by Django 4.2.1 on 2023-05-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isStaff',
        ),
    ]
