# Generated by Django 4.2.2 on 2023-06-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Treatment',
        ),
    ]
