# Generated by Django 4.2.1 on 2023-05-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_client_name_alter_appointment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.IntegerField(choices=[(900, '9:00'), (950, '9:30'), (1000, '10:00'), (1050, '10:30'), (1100, '11:00'), (1150, '11:30'), (1200, '12:00'), (1250, '12:30'), (1300, '13:00'), (1350, '13:30'), (1400, '14:00'), (1450, '14:30'), (1500, '15:00'), (1550, '15:30'), (1600, '16:00'), (1650, '16:30')], default=900),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
